name: black_tax_and_white_benefits
description: Mobile-friendly front end flutter app for
  blacktaxandwhitebenefits.com by Gordon Ferguson
version: 1.5.0+1500
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: 3.19.5 # should match main.yaml for CI pipeline.
  # yes, it would be worth considering ./flutterw or nvm
  # 3.19.5 is stable channel from March 27, 2024
dependencies:
  cached_network_image: 3.3.1
  dio: 5.4.3+1
  drift: 2.18.0
  firebase_analytics: 11.1.0
  firebase_crashlytics: 4.0.2
  flutter:
    sdk: flutter
  flutter_gen: 5.6.0
  flutter_hooks: 0.20.5
  flutter_html: any
  freezed_annotation: 2.4.1
  go_router: 14.2.0
  hooks_riverpod: 3.0.0-dev.3
  intl: 0.19.0
  json_annotation: 4.9.0
  logger: 2.3.0
  path: 1.9.0
  path_provider: 2.1.3
  retrofit: 4.1.0
  riverpod_annotation: 3.0.0-dev.3
  settings_ui: 2.0.2
  share_plus: 9.0.0
  shared_preferences: 2.2.3
  sqlite3_flutter_libs: 0.5.24
  url_launcher: 6.3.0

dev_dependencies:
  build_runner: 2.4.9
  drift_dev: 2.18.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: 2.5.2
  json_serializable: 6.8.0
  mocktail: 1.0.3
  retrofit_generator: 8.1.0
  riverpod_generator: 3.0.0-dev.11
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
  generate: true
