name: black_tax_and_white_benefits
description: Mobile-friendly front end flutter app for blacktaxandwhitebenefits.com by Gordon Ferguson
version: 1.5.0+1500
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
