name: black_tax_and_white_benefits
description: Mobile-friendly front end flutter app for
  blacktaxandwhitebenefits.com by Gordon Ferguson
version: 1.6.0+1600
publish_to: none

environment:
  sdk: "^3.5.0"
  flutter: 3.24.0  # should match version for main.yaml
dependencies:
  cached_network_image: ^3.4.0
  dio: 5.6.0
  drift: ^2.19.1+1
  firebase_analytics: 11.2.1
  firebase_crashlytics: 4.0.4
  flutter:
    sdk: flutter
  flutter_gen: 5.6.0
  flutter_hooks: 0.20.5
  flutter_html: any
  freezed_annotation: 2.4.4
  go_router: ^14.2.3
  hooks_riverpod: 3.0.0-dev.3
  intl: 0.19.0
  json_annotation: 4.9.0
  logger: ^2.4.0
  path: 1.9.0
  path_provider: ^2.1.4
  retrofit: 4.2.0
  riverpod_annotation: 3.0.0-dev.3
  settings_ui: 2.0.2
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  sqlite3_flutter_libs: 0.5.24
  url_launcher: 6.3.0
  
dev_dependencies:
  build_runner: 2.4.12
  drift_dev: 2.19.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: 2.5.7
  json_serializable: 6.8.0
  mocktail: 1.0.4
  retrofit_generator: ^8.2.0
  riverpod_generator: 3.0.0-dev.11
  very_good_analysis: 6.0.0

flutter:
  uses-material-design: true
  generate: true
