// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMjJwNDHTEIE-a0KaV7ey87P1y8VRRi-M',
    appId: '1:1033053592862:web:f34f4443b56afb598f3d0f',
    messagingSenderId: '1033053592862',
    projectId: 'black-tax-white-benefits-dev',
    authDomain: 'black-tax-white-benefits-dev.firebaseapp.com',
    storageBucket: 'black-tax-white-benefits-dev.appspot.com',
    measurementId: 'G-5X45MCVQG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnE2fLaBHUiNb9tOisqafzukrrezor9Ks',
    appId: '1:1033053592862:android:938383a35a61de508f3d0f',
    messagingSenderId: '1033053592862',
    projectId: 'black-tax-white-benefits-dev',
    storageBucket: 'black-tax-white-benefits-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0kY83Dkae-JerTEFc7rclmJ-T89wp2I',
    appId: '1:1033053592862:ios:3823fd04b0aef8a38f3d0f',
    messagingSenderId: '1033053592862',
    projectId: 'black-tax-white-benefits-dev',
    storageBucket: 'black-tax-white-benefits-dev.appspot.com',
    iosBundleId: 'com.blacktaxandwhitebenefits.gfapp.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC0kY83Dkae-JerTEFc7rclmJ-T89wp2I',
    appId: '1:1033053592862:ios:3823fd04b0aef8a38f3d0f',
    messagingSenderId: '1033053592862',
    projectId: 'black-tax-white-benefits-dev',
    storageBucket: 'black-tax-white-benefits-dev.appspot.com',
    iosBundleId: 'com.blacktaxandwhitebenefits.gfapp.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMjJwNDHTEIE-a0KaV7ey87P1y8VRRi-M',
    appId: '1:1033053592862:web:840e27b67b649ee48f3d0f',
    messagingSenderId: '1033053592862',
    projectId: 'black-tax-white-benefits-dev',
    authDomain: 'black-tax-white-benefits-dev.firebaseapp.com',
    storageBucket: 'black-tax-white-benefits-dev.appspot.com',
    measurementId: 'G-C8KGN2J93V',
  );
}
