// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2yxWEu205skPkBeGblVEYav9TL9NhI4Q',
    appId: '1:823282339018:web:126ac9b35c4cf9c042f833',
    messagingSenderId: '823282339018',
    projectId: 'black-tax-and-white-benefits',
    authDomain: 'black-tax-and-white-benefits.firebaseapp.com',
    databaseURL: 'https://black-tax-and-white-benefits.firebaseio.com',
    storageBucket: 'black-tax-and-white-benefits.appspot.com',
    measurementId: 'G-4H3YDMNG30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWPqo45AgRew8nKKZChpEY9YholFc1_l4',
    appId: '1:823282339018:android:e47e873e16b386ec42f833',
    messagingSenderId: '823282339018',
    projectId: 'black-tax-and-white-benefits',
    databaseURL: 'https://black-tax-and-white-benefits.firebaseio.com',
    storageBucket: 'black-tax-and-white-benefits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjs-8C_Fn7o8rXbfYI0KZSa5VKuxwbcA',
    appId: '1:823282339018:ios:d68c4decc7a883cc42f833',
    messagingSenderId: '823282339018',
    projectId: 'black-tax-and-white-benefits',
    databaseURL: 'https://black-tax-and-white-benefits.firebaseio.com',
    storageBucket: 'black-tax-and-white-benefits.appspot.com',
    androidClientId: '823282339018-7fbpbs5cpdkb8eeq05j006mc0gavssl6.apps.googleusercontent.com',
    iosBundleId: 'com.blacktaxandwhitebenefits.gfapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIjs-8C_Fn7o8rXbfYI0KZSa5VKuxwbcA',
    appId: '1:823282339018:ios:d68c4decc7a883cc42f833',
    messagingSenderId: '823282339018',
    projectId: 'black-tax-and-white-benefits',
    databaseURL: 'https://black-tax-and-white-benefits.firebaseio.com',
    storageBucket: 'black-tax-and-white-benefits.appspot.com',
    androidClientId: '823282339018-7fbpbs5cpdkb8eeq05j006mc0gavssl6.apps.googleusercontent.com',
    iosBundleId: 'com.blacktaxandwhitebenefits.gfapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2yxWEu205skPkBeGblVEYav9TL9NhI4Q',
    appId: '1:823282339018:web:3f6788256ea686ec42f833',
    messagingSenderId: '823282339018',
    projectId: 'black-tax-and-white-benefits',
    authDomain: 'black-tax-and-white-benefits.firebaseapp.com',
    databaseURL: 'https://black-tax-and-white-benefits.firebaseio.com',
    storageBucket: 'black-tax-and-white-benefits.appspot.com',
    measurementId: 'G-4HCFB7Y8ME',
  );
}
