// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDFpSsgfAx9qx_veu19_BOf0boWV4Wguc',
    appId: '1:951356165698:web:d160a849294bee284ee7db',
    messagingSenderId: '951356165698',
    projectId: 'black-tax-white-benefits-stg',
    authDomain: 'black-tax-white-benefits-stg.firebaseapp.com',
    storageBucket: 'black-tax-white-benefits-stg.appspot.com',
    measurementId: 'G-4060HRSRYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz3OH2z8LZ0MzjpExuhViLnLZ10MPNUxc',
    appId: '1:951356165698:android:fdacb135a73a782e4ee7db',
    messagingSenderId: '951356165698',
    projectId: 'black-tax-white-benefits-stg',
    storageBucket: 'black-tax-white-benefits-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXlxAsBKC-ncHPfpD_s_r3ghG1P4ucz14',
    appId: '1:951356165698:ios:0206eab37f8a51b44ee7db',
    messagingSenderId: '951356165698',
    projectId: 'black-tax-white-benefits-stg',
    storageBucket: 'black-tax-white-benefits-stg.appspot.com',
    iosBundleId: 'com.blacktaxandwhitebenefits.gfapp.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXlxAsBKC-ncHPfpD_s_r3ghG1P4ucz14',
    appId: '1:951356165698:ios:0206eab37f8a51b44ee7db',
    messagingSenderId: '951356165698',
    projectId: 'black-tax-white-benefits-stg',
    storageBucket: 'black-tax-white-benefits-stg.appspot.com',
    iosBundleId: 'com.blacktaxandwhitebenefits.gfapp.stg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDFpSsgfAx9qx_veu19_BOf0boWV4Wguc',
    appId: '1:951356165698:web:f6721632677bfa2e4ee7db',
    messagingSenderId: '951356165698',
    projectId: 'black-tax-white-benefits-stg',
    authDomain: 'black-tax-white-benefits-stg.firebaseapp.com',
    storageBucket: 'black-tax-white-benefits-stg.appspot.com',
    measurementId: 'G-XR6NF72QX6',
  );
}
